In [13]:
import numpy as np

# Day 1

In [28]:
f = open("input1.txt")
lines =f.readlines()
depth=np.array([int(x.strip()) for x in lines])

In [21]:
def num_increase(arr1):
    return np.sum((arr1[1:] - arr1[:-1])>0)

In [24]:
num_increase(depth)

1529

In [26]:
threesum_depth = (depth[2:] + depth[1:-1] + depth[:-2])
num_increase(threesum_depth)

1567

# Day 2

In [35]:
f = open("input2.txt")
lines =f.readlines()
dist = np.array([int(x.strip().split()[1]) for x in lines])
instr = [x.strip().split() for x in lines]
instr = [(x,int(y)) for x,y in instr]

In [41]:
class Sub:
    def __init__(self):
        self.depth = 0
        self.pos = 0
    def apply(self, d, val):
        if d == "forward":
            self.pos += val
        elif d == "down":
            self.depth += val
        elif d == "up":
            self.depth -= val


In [43]:
sub = Sub();
for x in instr:
    sub.apply(*x) 
print( sub.depth * sub.pos)

1250395


In [46]:
class Sub2:
    def __init__(self):
        self.depth = 0
        self.pos = 0
        self.aim = 0
    def apply(self, d, X):
        if d == "forward":
            self.pos += X
            self.depth += self.aim*X
        elif d == "down":
            self.aim += X
        elif d == "up":
            self.aim -= X


In [47]:
sub = Sub2();
for x in instr:
    sub.apply(*x) 
print( sub.depth * sub.pos)

1451210346


# Day 3

In [89]:
rep = """
00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
""".split()
bits = np.array([list(x) for x in rep], dtype=int)

In [113]:
f = open("input3.txt")
lines =f.readlines()
bits = np.array([list(x.strip()) for x in lines], dtype=int)

In [114]:
def maj(col):
    return 1 if (sum(col)>=len(col)/2) else 0
def mino(col):
    return 0 if (sum(col)>=len(col)/2) else 1
def convert(bbits):
    return sum(bbits*(2**(np.arange(len(bbits))[::-1])))

In [115]:
gamma_bits = np.array([maj(col) for col in bits.T])
epsilon_bits = np.array([mino(col) for col in bits.T])

In [116]:
convert(gamma_bits)*convert(epsilon_bits)

2972336

In [117]:
def filter(abits, pos, value):
    return abits[abits[:,pos] == value]

In [118]:
def oxy_co2(argbits, colop):
    abits = np.copy(argbits)
    pos = 0
    while len(abits)>1:
        abits = filter(abits, pos, colop(abits[:,pos]))
        pos += 1
    return convert(abits[0])

In [119]:
oxygen_rating = lambda x: oxy_co2(x, maj)
co2_rating = lambda x: oxy_co2(x, mino)

In [120]:
oxygen_rating(bits)*co2_rating(bits)

3368358

# Day 4

In [248]:
lines = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7"""
lines = lines.split("\n")
lines

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [283]:
f = open("input4.txt")
lines =f.readlines()
lines = [x.strip()  for x in lines]

In [284]:
bingo_nums = [ int(x) for x in lines[0].split(",")]

In [285]:
lines=lines[1:]

In [286]:
num_boards = len(lines)//6
boards =[]
bingos = []
for i in range(num_boards):
    board = lines[i*6+1:i*6+6]
    board = [[int(y) for y in x.split()] for x in board]
    boards +=[ board ]
    bingos += [np.ones((5,5))>1]
boards = np.array(boards)
bingos = np.array(bingos)

In [287]:
i=0
win_already = np.zeros(num_boards)>1
while not win_already.all():
    any_win = False
    while not any_win:
        bingos = bingos | (boards==bingo_nums[i])
        win = (bingos.all(axis = 1).any(axis=1)  | bingos.all(axis = 2).any(axis=1)) * (1-win_already)
        any_win = win.any()
        i+=1
    win_already = win_already|win
    win_idx = np.where(win)[0][0]
    win_board= boards[win_idx]
    win_bingo= bingos[win_idx]
    win_number = np.sum(win_board*(1-win_bingo))*bingo_nums[i-1]
    print(win_idx,win_number)


49 35711
14 72268
56 85360
76 47488
90 27047
57 7940
80 63832
8 19318
25 34731
39 34032
11 3805
32 43946
99 32021
38 42282
73 28938
1 45315
48 24210
6 39410
3 6006
27 4979
2 29550
79 36992
10 30456
13 30393
50 10912
15 24158
7 5268
33 515
20 17760
37 22632
24 1584
31 3186
0 50248
16 24300
59 34611
97 39936
12 25515
18 29766
35 7938
81 11664
5 27288
17 14364
86 0
40 13936
30 5586


# Day 5

In [421]:
lines = """0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2"""
lines = lines.split("\n")
lines

['0,9 -> 5,9',
 '8,0 -> 0,8',
 '9,4 -> 3,4',
 '2,2 -> 2,1',
 '7,0 -> 7,4',
 '6,4 -> 2,0',
 '0,9 -> 2,9',
 '3,4 -> 1,4',
 '0,0 -> 8,8',
 '5,5 -> 8,2']

In [441]:
f = open("input5.txt")
lines =f.readlines()
lines = [x.strip()  for x in lines]
#lines

In [442]:
parse = lambda x: [int(y) for y in x.split(",")]
a=[ x.split(" -> ") for x in lines]
b =np.array([ [parse(x),parse(y)] for x,y in a])

In [443]:
c= np.array([ x  for p in b for x in p])
grid = np.zeros(c.max(axis=0)+1)

In [444]:
for start,end in b:
    if (start == end)[1]:
        grid[min(start[0],end[0]):max(start[0],end[0]),start[1]]+=1
        grid[max(start[0],end[0]),start[1]]+=1
    elif (start == end)[0] :
        grid[start[0],min(start[1],end[1]):max(start[1],end[1])]+=1
        grid[start[0],max(start[1],end[1])]+=1


In [445]:
grid.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [446]:
np.sum(grid>=2)

8622

In [447]:
def line(start,end):
    val = start.copy()
    vals = [val.copy()]
    while not (val == end).all():
        val+=1-2*(start>end)
        vals+=[val.copy()]
    return np.array(vals).T

In [448]:
x,y = line(np.array([3,3]),np.array([5,5]))
x

array([3, 4, 5])

In [449]:
grid = np.zeros(c.max(axis=0)+1)

In [450]:
for start,end in b:
    if (start == end)[1]:
        grid[min(start[0],end[0]):max(start[0],end[0]),start[1]]+=1
        grid[max(start[0],end[0]),start[1]]+=1
    elif (start == end)[0] :
        grid[start[0],min(start[1],end[1]):max(start[1],end[1])]+=1
        grid[start[0],max(start[1],end[1])]+=1
    else:
        x,y = line(start,end)
        grid[x,y]+=1

In [451]:
grid.T

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [452]:
np.sum(grid>=2)

22037

# Day 6

In [518]:
line ="3,4,3,1,2"
line

'3,4,3,1,2'

In [524]:
f = open("input6.txt")
lines =f.readlines()
line = lines[0].strip()
line

'1,1,3,1,3,2,1,3,1,1,3,1,1,2,1,3,1,1,3,5,1,1,1,3,1,2,1,1,1,1,4,4,1,2,1,2,1,1,1,5,3,2,1,5,2,5,3,3,2,2,5,4,1,1,4,4,1,1,1,1,1,1,5,1,2,4,3,2,2,2,2,1,4,1,1,5,1,3,4,4,1,1,3,3,5,5,3,1,3,3,3,1,4,2,2,1,3,4,1,4,3,3,2,3,1,1,1,5,3,1,4,2,2,3,1,3,1,2,3,3,1,4,2,2,4,1,3,1,1,1,1,1,2,1,3,3,1,2,1,1,3,4,1,1,1,1,5,1,1,5,1,1,1,4,1,5,3,1,1,3,2,1,1,3,1,1,1,5,4,3,3,5,1,3,4,3,3,1,4,4,1,2,1,1,2,1,1,1,2,1,1,1,1,1,5,1,1,2,1,5,2,1,1,2,3,2,3,1,3,1,1,1,5,1,1,2,1,1,1,1,3,4,5,3,1,4,1,1,4,1,4,1,1,1,4,5,1,1,1,4,1,3,2,2,1,1,2,3,1,4,3,5,1,5,1,1,4,5,5,1,1,3,3,1,1,1,1,5,5,3,3,2,4,1,1,1,1,1,5,1,1,2,5,5,4,2,4,4,1,1,3,3,1,5,1,1,1,1,1,1'

In [525]:
ages = [int(x) for x in line.split(",")]

In [526]:
from collections import defaultdict

In [527]:
np.arange(8)+1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [528]:
num = defaultdict(int)
for age in ages:
    num[age]+=1

In [529]:
for i in range(256):
    new_num = defaultdict(int)
    for age in np.arange(8)+1:
        new_num[age-1] = num[age]
    new_num[8] += num[0]
    new_num[6] += num[0]
    num = new_num
print(sum([num[x] for x in range(9)]))

1682576647495
